site_name: Gerb documentation
theme:
  name: cinder

nav:
  - Home: index.md
  - Backend services: backend.md
  - Frontend services: frontend.md
  - User Interface: ui.md
  - Troubleshooting: troubleshoot.md

site_url: ""
use_directory_urls: false