version: "3"
services:
  api:
    build: .
    ports:
    - 6969:6969

    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=siri2251105
      - DATABASE_NAME=gerb
      - DATABASE_USERNAME=postgres
      - SECRET_KEY="09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=30


